In [1]:
import numpy as np
import pandas as pd 
from keras.preprocessing.image import ImageDataGenerator, load_img
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import random
import os
import zipfile
#print(os.listdir("../input"))

In [2]:
def extract_files(source_path, target_path):
    zip_ref = zipfile.ZipFile(source_path,'r')
    zip_ref.extractall(target_path)
    zip_ref.close()

In [3]:
#extract_files('test1.zip','desktop/test')
extract_files('train.zip','desktop/train')

In [4]:
count = 0
for img in os.listdir("desktop/train/train"):
    print(img.split(".")[0])
    #print("hello")
    count = count + 1 
    if count > 3:
        break

cat
cat
cat
cat


In [5]:
import cv2
main_dir = "desktop/train/"
train_dir = "train"
path = os.path.join(main_dir,train_dir)
X = []
Y = []
for img in os.listdir("desktop/train/train"):
    category = img.split(".")[0]
    img_array = cv2.imread(os.path.join(path,img))
    new_img_array = cv2.resize(img_array, dsize=(150, 150))
    #image = load_img(os.path.join(path,img))
    #plt.figure()
    #plt.imshow(image)
    X.append(new_img_array)
    Y.append(category)


In [6]:
X= np.array(X)
X.shape

(25000, 150, 150, 3)

In [7]:
Y=np.array(Y)
Y.shape

(25000,)

In [8]:
y_df = pd.DataFrame(Y)
y_df[0]=y_df[0].replace({"dog":1 , "cat":0})
Y = np.array(y_df[0])
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [9]:
X= X/255

In [10]:
X

array([[[[0.34117647, 0.64313725, 0.79607843],
         [0.36078431, 0.6627451 , 0.81568627],
         [0.36470588, 0.66666667, 0.81960784],
         ...,
         [0.48235294, 0.80784314, 0.96862745],
         [0.47058824, 0.79607843, 0.95686275],
         [0.47843137, 0.78823529, 0.94117647]],

        [[0.34117647, 0.64313725, 0.79607843],
         [0.36078431, 0.6627451 , 0.81568627],
         [0.36470588, 0.66666667, 0.81960784],
         ...,
         [0.48627451, 0.81176471, 0.96078431],
         [0.4745098 , 0.8       , 0.96078431],
         [0.47843137, 0.78823529, 0.94117647]],

        [[0.34117647, 0.64313725, 0.79607843],
         [0.36078431, 0.6627451 , 0.81568627],
         [0.36470588, 0.66666667, 0.81960784],
         ...,
         [0.49803922, 0.81568627, 0.96470588],
         [0.49019608, 0.80784314, 0.95686275],
         [0.48627451, 0.79607843, 0.94901961]],

        ...,

        [[0.21176471, 0.48627451, 0.61568627],
         [0.21568627, 0.49019608, 0.61960784]

In [11]:
X = X.reshape(25000, 150,150,3)

In [12]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, Activation, BatchNormalization
model = Sequential()

# 3 Convolutional, Pooling, Dropout layers
model.add(Conv2D(8, 
                 (3,3), 
                 activation = 'relu', 
                 input_shape = (150, 150, 3)))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.25))

model.add(Conv2D(16, 
                 (3, 3),
                 activation = 'relu'))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.25))

model.add(Conv2D(32, 
                 (3,3), 
                 activation = 'relu'))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.25))

# Dense layers start
model.add(Flatten())

model.add(Dense(1024, 
                activation = 'relu'))
model.add(Dropout(0.45))

model.add(Dense(256, 
                activation = 'tanh'))
model.add(Dropout(0.45))

model.add(Dense(1, 
                activation = 'sigmoid'))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 148, 148, 8)       224       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 74, 74, 8)         0         
_________________________________________________________________
dropout (Dropout)            (None, 74, 74, 8)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 72, 72, 16)        1168      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 36, 36, 16)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 36, 36, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 34, 34, 32)        4

In [14]:
model.compile(loss = 'binary_crossentropy', 
              optimizer = 'adam',
              metrics = ['accuracy'])

In [15]:
model.fit(X, Y, epochs=2, batch_size=32, validation_split=0.2)

Epoch 1/2
625/625 [==============================] - 125s 198ms/step - loss: 0.6873 - accuracy: 0.6385 - val_loss: 1.5321 - val_accuracy: 0.1798
Epoch 2/2
625/625 [==============================] - 104s 166ms/step - loss: 0.5426 - accuracy: 0.7261 - val_loss: 0.9155 - val_accuracy: 0.4434


In [16]:
def upload(path):
    img_array = cv2.imread(path)
    new_img_array = cv2.resize(img_array, dsize=(150, 150))
    #new img_array= np.array(new_img_array)
    return new_img_array

In [43]:
upload("C:\\Users\\LENOVO\\Desktop\\train\\train\\cat.6627.jpg")
new_img_array.shape

(1, 150, 150, 3)

In [44]:
new_img_array = new_img_array.reshape(-1,150,150,3)
new_img_array = new_img_array/255

In [45]:
new_img_array.shape

(1, 150, 150, 3)

In [46]:
predictions = model.predict(new_img_array)

In [48]:
predictions

array([[0.05273286]], dtype=float32)